#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 8004


#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  
#日志
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/payment8004.log
  #日志文件最大xxMB
  maxSize: 30MB 
  #保存xx天的日志
  maxHistory: 20
  #日志文件所在储存空间最大xxGB
  totalSizeCap: 10GB


