server:
  port: 80

spring:
  application:
    name: cloud-order-service
    
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka      
  instance:
    instance-id: orderFeign80
    #访问路径可以显示IP地址
    prefer-ip-address: true
      
#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000


#日志
logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.lzd.springcloud.service.PaymentFeignService: debug
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/consumer-order80.log
  #日志文件最大xxMB
  maxSize: 30MB 
  #保存xx天的日志
  maxHistory: 20
  #日志文件所在储存空间最大xxGB
  totalSizeCap: 10GB


