###consul服务端口号
server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
####consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
#日志
logging:
  config: classpath:logback-admin.xml
log:
  level:
    root: info
    my: debug
  file: logs/paymentconsul8006.log
  #日志文件最大xxMB
  maxSize: 30MB 
  #保存xx天的日志
  maxHistory: 20
  #日志文件所在储存空间最大xxGB
  totalSizeCap: 10GB


